const express = require("express");
const cors = require("cors");
const app = express();
const DB = "stellar";
const PORT = 8000;
app.use(cors());
app.use(express.json(),express.urlencoded({extended:true}));
require("./config/mongoose.config")(DB);
require("./routes/user.routes")(app);
app.listen(PORT,()=>console.log(`port: ${PORT}`));